// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gameboy.command.messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Retro.Net.Api.RealTime.Messages.Command {

  /// <summary>Holder for reflection information generated from gameboy.command.messages.proto</summary>
  public static partial class GameboyCommandMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for gameboy.command.messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameboyCommandMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5nYW1lYm95LmNvbW1hbmQubWVzc2FnZXMucHJvdG8aHmdhbWVib3kuY29t",
            "bWFuZC5kZWJ1Z2dlci5wcm90byIZCglIZWFydEJlYXQSDAoEZGF0ZRgBIAEo",
            "CSIsChVTZXRHYW1lQm95Q2xpZW50U3RhdGUSEwoLZGlzcGxheU5hbWUYASAB",
            "KAkiRwofUmVxdWVzdEdhbWVCb3lKb3lQYWRCdXR0b25QcmVzcxIkCgZidXR0",
            "b24YASABKA4yFC5HYW1lQm95Sm95UGFkQnV0dG9uIskBChZHYW1lQm95RGVi",
            "dWdnZXJDb21tYW5kEicKDWFkZEJyZWFrcG9pbnQYASABKAsyDi5BZGRCcmVh",
            "a3BvaW50SAASLQoQcmVtb3ZlQnJlYWtwb2ludBgCIAEoCzIRLlJlbW92ZUJy",
            "ZWFrcG9pbnRIABIpCg5nZXRCcmVha3BvaW50cxgDIAEoCzIPLkdldEJyZWFr",
            "cG9pbnRzSAASIwoHY29tbWFuZBgEIAEoDjIQLkRlYnVnZ2VyQ29tbWFuZEgA",
            "QgcKBXZhbHVlKmsKE0dhbWVCb3lKb3lQYWRCdXR0b24SCAoETk9ORRAAEgYK",
            "AlVQEAESCAoERE9XThACEggKBExFRlQQAxIJCgVSSUdIVBAEEgUKAUEQBRIF",
            "CgFCEAYSCQoFU1RBUlQQBxIKCgZTRUxFQ1QQCEIqqgInUmV0cm8uTmV0LkFw",
            "aS5SZWFsVGltZS5NZXNzYWdlcy5Db21tYW5kYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Retro.Net.Api.RealTime.Messages.Command.Debugger.GameboyCommandDebuggerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Retro.Net.Api.RealTime.Messages.Command.GameBoyJoyPadButton), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Retro.Net.Api.RealTime.Messages.Command.HeartBeat), global::Retro.Net.Api.RealTime.Messages.Command.HeartBeat.Parser, new[]{ "Date" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Retro.Net.Api.RealTime.Messages.Command.SetGameBoyClientState), global::Retro.Net.Api.RealTime.Messages.Command.SetGameBoyClientState.Parser, new[]{ "DisplayName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Retro.Net.Api.RealTime.Messages.Command.RequestGameBoyJoyPadButtonPress), global::Retro.Net.Api.RealTime.Messages.Command.RequestGameBoyJoyPadButtonPress.Parser, new[]{ "Button" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Retro.Net.Api.RealTime.Messages.Command.GameBoyDebuggerCommand), global::Retro.Net.Api.RealTime.Messages.Command.GameBoyDebuggerCommand.Parser, new[]{ "AddBreakpoint", "RemoveBreakpoint", "GetBreakpoints", "Command" }, new[]{ "Value" }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// A button on the GameBoy joypad.
  /// </summary>
  public enum GameBoyJoyPadButton {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("UP")] Up = 1,
    [pbr::OriginalName("DOWN")] Down = 2,
    [pbr::OriginalName("LEFT")] Left = 3,
    [pbr::OriginalName("RIGHT")] Right = 4,
    [pbr::OriginalName("A")] A = 5,
    [pbr::OriginalName("B")] B = 6,
    [pbr::OriginalName("START")] Start = 7,
    [pbr::OriginalName("SELECT")] Select = 8,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Just a heartbeat to keep the connection alive.
  /// </summary>
  public sealed partial class HeartBeat : pb::IMessage<HeartBeat> {
    private static readonly pb::MessageParser<HeartBeat> _parser = new pb::MessageParser<HeartBeat>(() => new HeartBeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeartBeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Retro.Net.Api.RealTime.Messages.Command.GameboyCommandMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartBeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartBeat(HeartBeat other) : this() {
      date_ = other.date_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartBeat Clone() {
      return new HeartBeat(this);
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 1;
    private string date_ = "";
    /// <summary>
    /// The date of the heartbeat.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Date {
      get { return date_; }
      set {
        date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeartBeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeartBeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Date != other.Date) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Date.Length != 0) hash ^= Date.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Date.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Date);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Date.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeartBeat other) {
      if (other == null) {
        return;
      }
      if (other.Date.Length != 0) {
        Date = other.Date;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Date = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Command to set the state of a GameBoy websocket connection.
  /// </summary>
  public sealed partial class SetGameBoyClientState : pb::IMessage<SetGameBoyClientState> {
    private static readonly pb::MessageParser<SetGameBoyClientState> _parser = new pb::MessageParser<SetGameBoyClientState>(() => new SetGameBoyClientState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetGameBoyClientState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Retro.Net.Api.RealTime.Messages.Command.GameboyCommandMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetGameBoyClientState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetGameBoyClientState(SetGameBoyClientState other) : this() {
      displayName_ = other.displayName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetGameBoyClientState Clone() {
      return new SetGameBoyClientState(this);
    }

    /// <summary>Field number for the "displayName" field.</summary>
    public const int DisplayNameFieldNumber = 1;
    private string displayName_ = "";
    /// <summary>
    /// The new display name associated with the connected GameBoy client.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetGameBoyClientState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetGameBoyClientState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DisplayName != other.DisplayName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DisplayName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DisplayName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetGameBoyClientState other) {
      if (other == null) {
        return;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DisplayName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Command to press a button on the GameBoy joypad.
  /// </summary>
  public sealed partial class RequestGameBoyJoyPadButtonPress : pb::IMessage<RequestGameBoyJoyPadButtonPress> {
    private static readonly pb::MessageParser<RequestGameBoyJoyPadButtonPress> _parser = new pb::MessageParser<RequestGameBoyJoyPadButtonPress>(() => new RequestGameBoyJoyPadButtonPress());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestGameBoyJoyPadButtonPress> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Retro.Net.Api.RealTime.Messages.Command.GameboyCommandMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestGameBoyJoyPadButtonPress() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestGameBoyJoyPadButtonPress(RequestGameBoyJoyPadButtonPress other) : this() {
      button_ = other.button_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestGameBoyJoyPadButtonPress Clone() {
      return new RequestGameBoyJoyPadButtonPress(this);
    }

    /// <summary>Field number for the "button" field.</summary>
    public const int ButtonFieldNumber = 1;
    private global::Retro.Net.Api.RealTime.Messages.Command.GameBoyJoyPadButton button_ = 0;
    /// <summary>
    /// The requested button to press.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Retro.Net.Api.RealTime.Messages.Command.GameBoyJoyPadButton Button {
      get { return button_; }
      set {
        button_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestGameBoyJoyPadButtonPress);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestGameBoyJoyPadButtonPress other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Button != other.Button) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Button != 0) hash ^= Button.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Button != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Button);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Button != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Button);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestGameBoyJoyPadButtonPress other) {
      if (other == null) {
        return;
      }
      if (other.Button != 0) {
        Button = other.Button;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            button_ = (global::Retro.Net.Api.RealTime.Messages.Command.GameBoyJoyPadButton) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A command sent to the GameBoy debugger.
  /// </summary>
  public sealed partial class GameBoyDebuggerCommand : pb::IMessage<GameBoyDebuggerCommand> {
    private static readonly pb::MessageParser<GameBoyDebuggerCommand> _parser = new pb::MessageParser<GameBoyDebuggerCommand>(() => new GameBoyDebuggerCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameBoyDebuggerCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Retro.Net.Api.RealTime.Messages.Command.GameboyCommandMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameBoyDebuggerCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameBoyDebuggerCommand(GameBoyDebuggerCommand other) : this() {
      switch (other.ValueCase) {
        case ValueOneofCase.AddBreakpoint:
          AddBreakpoint = other.AddBreakpoint.Clone();
          break;
        case ValueOneofCase.RemoveBreakpoint:
          RemoveBreakpoint = other.RemoveBreakpoint.Clone();
          break;
        case ValueOneofCase.GetBreakpoints:
          GetBreakpoints = other.GetBreakpoints.Clone();
          break;
        case ValueOneofCase.Command:
          Command = other.Command;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameBoyDebuggerCommand Clone() {
      return new GameBoyDebuggerCommand(this);
    }

    /// <summary>Field number for the "addBreakpoint" field.</summary>
    public const int AddBreakpointFieldNumber = 1;
    /// <summary>
    /// Adds a breakpoint to the debugger.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Retro.Net.Api.RealTime.Messages.Command.Debugger.AddBreakpoint AddBreakpoint {
      get { return valueCase_ == ValueOneofCase.AddBreakpoint ? (global::Retro.Net.Api.RealTime.Messages.Command.Debugger.AddBreakpoint) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.AddBreakpoint;
      }
    }

    /// <summary>Field number for the "removeBreakpoint" field.</summary>
    public const int RemoveBreakpointFieldNumber = 2;
    /// <summary>
    /// Removes a breakpoint from the debugger.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Retro.Net.Api.RealTime.Messages.Command.Debugger.RemoveBreakpoint RemoveBreakpoint {
      get { return valueCase_ == ValueOneofCase.RemoveBreakpoint ? (global::Retro.Net.Api.RealTime.Messages.Command.Debugger.RemoveBreakpoint) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.RemoveBreakpoint;
      }
    }

    /// <summary>Field number for the "getBreakpoints" field.</summary>
    public const int GetBreakpointsFieldNumber = 3;
    /// <summary>
    /// Gets all defined breakpoints.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Retro.Net.Api.RealTime.Messages.Command.Debugger.GetBreakpoints GetBreakpoints {
      get { return valueCase_ == ValueOneofCase.GetBreakpoints ? (global::Retro.Net.Api.RealTime.Messages.Command.Debugger.GetBreakpoints) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.GetBreakpoints;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 4;
    /// <summary>
    /// A debugger command.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Retro.Net.Api.RealTime.Messages.Command.Debugger.DebuggerCommand Command {
      get { return valueCase_ == ValueOneofCase.Command ? (global::Retro.Net.Api.RealTime.Messages.Command.Debugger.DebuggerCommand) value_ : 0; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.Command;
      }
    }

    private object value_;
    /// <summary>Enum of possible cases for the "value" oneof.</summary>
    public enum ValueOneofCase {
      None = 0,
      AddBreakpoint = 1,
      RemoveBreakpoint = 2,
      GetBreakpoints = 3,
      Command = 4,
    }
    private ValueOneofCase valueCase_ = ValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueOneofCase ValueCase {
      get { return valueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearValue() {
      valueCase_ = ValueOneofCase.None;
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameBoyDebuggerCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameBoyDebuggerCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AddBreakpoint, other.AddBreakpoint)) return false;
      if (!object.Equals(RemoveBreakpoint, other.RemoveBreakpoint)) return false;
      if (!object.Equals(GetBreakpoints, other.GetBreakpoints)) return false;
      if (Command != other.Command) return false;
      if (ValueCase != other.ValueCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (valueCase_ == ValueOneofCase.AddBreakpoint) hash ^= AddBreakpoint.GetHashCode();
      if (valueCase_ == ValueOneofCase.RemoveBreakpoint) hash ^= RemoveBreakpoint.GetHashCode();
      if (valueCase_ == ValueOneofCase.GetBreakpoints) hash ^= GetBreakpoints.GetHashCode();
      if (valueCase_ == ValueOneofCase.Command) hash ^= Command.GetHashCode();
      hash ^= (int) valueCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (valueCase_ == ValueOneofCase.AddBreakpoint) {
        output.WriteRawTag(10);
        output.WriteMessage(AddBreakpoint);
      }
      if (valueCase_ == ValueOneofCase.RemoveBreakpoint) {
        output.WriteRawTag(18);
        output.WriteMessage(RemoveBreakpoint);
      }
      if (valueCase_ == ValueOneofCase.GetBreakpoints) {
        output.WriteRawTag(26);
        output.WriteMessage(GetBreakpoints);
      }
      if (valueCase_ == ValueOneofCase.Command) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (valueCase_ == ValueOneofCase.AddBreakpoint) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddBreakpoint);
      }
      if (valueCase_ == ValueOneofCase.RemoveBreakpoint) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RemoveBreakpoint);
      }
      if (valueCase_ == ValueOneofCase.GetBreakpoints) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetBreakpoints);
      }
      if (valueCase_ == ValueOneofCase.Command) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameBoyDebuggerCommand other) {
      if (other == null) {
        return;
      }
      switch (other.ValueCase) {
        case ValueOneofCase.AddBreakpoint:
          if (AddBreakpoint == null) {
            AddBreakpoint = new global::Retro.Net.Api.RealTime.Messages.Command.Debugger.AddBreakpoint();
          }
          AddBreakpoint.MergeFrom(other.AddBreakpoint);
          break;
        case ValueOneofCase.RemoveBreakpoint:
          if (RemoveBreakpoint == null) {
            RemoveBreakpoint = new global::Retro.Net.Api.RealTime.Messages.Command.Debugger.RemoveBreakpoint();
          }
          RemoveBreakpoint.MergeFrom(other.RemoveBreakpoint);
          break;
        case ValueOneofCase.GetBreakpoints:
          if (GetBreakpoints == null) {
            GetBreakpoints = new global::Retro.Net.Api.RealTime.Messages.Command.Debugger.GetBreakpoints();
          }
          GetBreakpoints.MergeFrom(other.GetBreakpoints);
          break;
        case ValueOneofCase.Command:
          Command = other.Command;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Retro.Net.Api.RealTime.Messages.Command.Debugger.AddBreakpoint subBuilder = new global::Retro.Net.Api.RealTime.Messages.Command.Debugger.AddBreakpoint();
            if (valueCase_ == ValueOneofCase.AddBreakpoint) {
              subBuilder.MergeFrom(AddBreakpoint);
            }
            input.ReadMessage(subBuilder);
            AddBreakpoint = subBuilder;
            break;
          }
          case 18: {
            global::Retro.Net.Api.RealTime.Messages.Command.Debugger.RemoveBreakpoint subBuilder = new global::Retro.Net.Api.RealTime.Messages.Command.Debugger.RemoveBreakpoint();
            if (valueCase_ == ValueOneofCase.RemoveBreakpoint) {
              subBuilder.MergeFrom(RemoveBreakpoint);
            }
            input.ReadMessage(subBuilder);
            RemoveBreakpoint = subBuilder;
            break;
          }
          case 26: {
            global::Retro.Net.Api.RealTime.Messages.Command.Debugger.GetBreakpoints subBuilder = new global::Retro.Net.Api.RealTime.Messages.Command.Debugger.GetBreakpoints();
            if (valueCase_ == ValueOneofCase.GetBreakpoints) {
              subBuilder.MergeFrom(GetBreakpoints);
            }
            input.ReadMessage(subBuilder);
            GetBreakpoints = subBuilder;
            break;
          }
          case 32: {
            value_ = input.ReadEnum();
            valueCase_ = ValueOneofCase.Command;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
